//-------+---------+---------+---------+---------+---------+---------+---------+
// Copyright (c) 1991-1992 Betz Associates. All rights reserved.
//
// File Name: DETECT.H
// Project:   Flights of Fantasy
// Creation:  August 20, 1992
// Author:    Mark Betz (MB)
//
// Machine:   IBM PC and Compatibles
//
// Includes:  nothing
//
//-------+---------+---------+---------+---------+---------+---------+---------+
// Change History
// ------ -------
//
//      Date            Rev.	Author		Purpose
//      ----            ----    ------      -------
//      8-29-1992       1.1b    MB          first beta
//      9-26-1992       1.1     MB          publication release
//
// Description
// -----------
//      function prototype for 386/486 cpu detection
//-------+---------+---------+---------+---------+---------+---------+---------+

#ifndef __DETECT__
#define __DETECT__

extern "C" boolean detect386();

#endif